/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveAlert: typeof import('./components/ActiveAlert.vue')['default']
    AutoMacro: typeof import('./components/AutoMacro.vue')['default']
    ChannelPoint: typeof import('./components/ChannelPoint.vue')['default']
    Giveaway: typeof import('./components/Giveaway.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    KeyboardOverlay: typeof import('./components/overlays/KeyboardOverlay.vue')['default']
    Macro: typeof import('./components/Macro.vue')['default']
    MusicControls: typeof import('./components/MusicControls.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    ObsAudio: typeof import('./components/obs/ObsAudio.vue')['default']
    PowerDialog: typeof import('./components/dialogs/PowerDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/panels/SettingsPanel.vue')['default']
    WifiNetworkDialog: typeof import('./components/dialogs/WifiNetworkDialog.vue')['default']
    WifiSettingsCard: typeof import('./components/cards/WifiSettingsCard.vue')['default']
    WiredSettingsCard: typeof import('./components/cards/WiredSettingsCard.vue')['default']
    YoloboxAudio: typeof import('./components/yolobox/YoloboxAudio.vue')['default']
  }
}
