/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audio': RouteRecordInfo<
      '/audio',
      '/audio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/channelPoints': RouteRecordInfo<
      '/channelPoints',
      '/channelPoints',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/macros': RouteRecordInfo<
      '/macros',
      '/macros',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recovery': RouteRecordInfo<
      '/recovery',
      '/recovery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/songlist': RouteRecordInfo<
      '/songlist',
      '/songlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
      views:
        | never
    }
    'src/pages/audio.vue': {
      routes:
        | '/audio'
      views:
        | never
    }
    'src/pages/channelPoints.vue': {
      routes:
        | '/channelPoints'
      views:
        | never
    }
    'src/pages/macros.vue': {
      routes:
        | '/macros'
      views:
        | never
    }
    'src/pages/recovery.vue': {
      routes:
        | '/recovery'
      views:
        | never
    }
    'src/pages/songlist.vue': {
      routes:
        | '/songlist'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
